package org.example.fuzzy_app;

import java.text.Normalizer;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;


public class Normalize {
    public static final Map<Character, Character> normalized = new HashMap<>(Map.ofEntries(
            Map.entry('ⁱ', 'i'),
            Map.entry('ₕ', 'h'),
            Map.entry('ₖ', 'k'),
            Map.entry('ₗ', 'l'),
            Map.entry('ₘ', 'm'),
            Map.entry('ₙ', 'n'),
            Map.entry('ₚ', 'p'),
            Map.entry('ₛ', 's'),
            Map.entry('ₜ', 't'),
            Map.entry('Ø', 'O'),
            Map.entry('ß', 's'),
            Map.entry('ø', 'o'),
            Map.entry('ᴀ', 'A'),
            Map.entry('ᴃ', 'B'),
            Map.entry('ᴄ', 'C'),
            Map.entry('ᴅ', 'D'),
            Map.entry('ᴇ', 'E'),
            Map.entry('ᴈ', 'e'),
            Map.entry('ᴉ', 'i'),
            Map.entry('ᴊ', 'J'),
            Map.entry('ᴋ', 'K'),
            Map.entry('ᴌ', 'L'),
            Map.entry('ᴍ', 'M'),
            Map.entry('ᴎ', 'N'),
            Map.entry('ᴏ', 'O'),
            Map.entry('ᴐ', 'O'),
            Map.entry('ᴑ', 'o'),
            Map.entry('đ', 'd'),
            Map.entry('ᴒ', 'o'),
            Map.entry('ᴓ', 'o'),
            Map.entry('ᴖ', 'o'),
            Map.entry('ᴗ', 'o'),
            Map.entry('ᴘ', 'P'),
            Map.entry('ᴙ', 'R'),
            Map.entry('ᴚ', 'R'),
            Map.entry('ᴛ', 'T'),
            Map.entry('ᴜ', 'U'),
            Map.entry('ᴝ', 'u'),
            Map.entry('ᴞ', 'u'),
            Map.entry('ᴟ', 'm'),
            Map.entry('ᴠ', 'V'),
            Map.entry('ᴡ', 'W'),
            Map.entry('ᴢ', 'Z'),
            Map.entry('ħ', 'h'),
            Map.entry('ı', 'i'),
            Map.entry('ŀ', 'l'),
            Map.entry('ł', 'l'),
            Map.entry('ᵢ', 'i'),
            Map.entry('ᵣ', 'r'),
            Map.entry('ᵤ', 'u'),
            Map.entry('ᵥ', 'v'),
            Map.entry('ŧ', 't'),
            Map.entry('ſ', 's'),
            Map.entry('ƀ', 'b'),
            Map.entry('Ɓ', 'B'),
            Map.entry('ƃ', 'b'),
            Map.entry('ↄ', 'c'),
            Map.entry('Ɔ', 'O'),
            Map.entry('ƈ', 'c'),
            Map.entry('Ɖ', 'D'),
            Map.entry('Ɗ', 'D'),
            Map.entry('ƌ', 'd'),
            Map.entry('Ǝ', 'E'),
            Map.entry('Ɛ', 'E'),
            Map.entry('ƒ', 'f'),
            Map.entry('Ɠ', 'G'),
            Map.entry('Ɨ', 'I'),
            Map.entry('ƙ', 'k'),
            Map.entry('ƚ', 'l'),
            Map.entry('Ɯ', 'M'),
            Map.entry('Ɲ', 'N'),
            Map.entry('ƞ', 'n'),
            Map.entry('Ɵ', 'O'),
            Map.entry('ƥ', 'p'),
            Map.entry('ƫ', 't'),
            Map.entry('ƭ', 't'),
            Map.entry('Ʈ', 'T'),
            Map.entry('Ʋ', 'V'),
            Map.entry('ƴ', 'y'),
            Map.entry('ƶ', 'z'),
            Map.entry('ǝ', 'e'),
            Map.entry('ǥ', 'g'),
            Map.entry('Ƞ', 'N'),
            Map.entry('ȡ', 'd'),
            Map.entry('ȥ', 'z'),
            Map.entry('ȴ', 'l'),
            Map.entry('ȵ', 'n'),
            Map.entry('ȶ', 't'),
            Map.entry('ȷ', 'j'),
            Map.entry('Ⱥ', 'A'),
            Map.entry('Ȼ', 'C'),
            Map.entry('ȼ', 'c'),
            Map.entry('Ƚ', 'L'),
            Map.entry('Ⱦ', 'T'),
            Map.entry('ȿ', 's'),
            Map.entry('ɀ', 'z'),
            Map.entry('Ƀ', 'B'),
            Map.entry('Ʉ', 'U'),
            Map.entry('Ʌ', 'V'),
            Map.entry('Ɇ', 'E'),
            Map.entry('ɇ', 'e'),
            Map.entry('Ɉ', 'J'),
            Map.entry('ɉ', 'j'),
            Map.entry('Ɋ', 'Q'),
            Map.entry('ɋ', 'q'),
            Map.entry('Ɍ', 'R'),
            Map.entry('ɍ', 'r'),
            Map.entry('Ɏ', 'Y'),
            Map.entry('ɏ', 'y'),
            Map.entry('ɐ', 'a'),
            Map.entry('ɑ', 'a'),
            Map.entry('ɓ', 'b'),
            Map.entry('ɔ', 'o'),
            Map.entry('ɕ', 'c'),
            Map.entry('ɖ', 'd'),
            Map.entry('ɗ', 'd'),
            Map.entry('ɘ', 'e'),
            Map.entry('ɛ', 'e'),
            Map.entry('ɜ', 'e'),
            Map.entry('ɝ', 'e'),
            Map.entry('ɞ', 'e'),
            Map.entry('ɟ', 'j'),
            Map.entry('ɠ', 'g'),
            Map.entry('ɡ', 'g'),
            Map.entry('ɢ', 'G'),
            Map.entry('ɥ', 'h'),
            Map.entry('ɦ', 'h'),
            Map.entry('ɨ', 'i'),
            Map.entry('ɪ', 'I'),
            Map.entry('ɫ', 'l'),
            Map.entry('ɬ', 'l'),
            Map.entry('ɭ', 'l'),
            Map.entry('ɯ', 'm'),
            Map.entry('ɰ', 'm'),
            Map.entry('ɱ', 'm'),
            Map.entry('ɲ', 'n'),
            Map.entry('ɳ', 'n'),
            Map.entry('ɴ', 'N'),
            Map.entry('ɵ', 'o'),
            Map.entry('ɹ', 'r'),
            Map.entry('ɺ', 'r'),
            Map.entry('ɻ', 'r'),
            Map.entry('ɼ', 'r'),
            Map.entry('ɽ', 'r'),
            Map.entry('ɾ', 'r'),
            Map.entry('ɿ', 'r'),
            Map.entry('ʀ', 'R'),
            Map.entry('ʁ', 'R'),
            Map.entry('ʂ', 's'),
            Map.entry('ʇ', 't'),
            Map.entry('ʈ', 't'),
            Map.entry('ʉ', 'u'),
            Map.entry('ʋ', 'v'),
            Map.entry('ʌ', 'v'),
            Map.entry('ʍ', 'w'),
            Map.entry('ʎ', 'y'),
            Map.entry('ʏ', 'Y'),
            Map.entry('ʐ', 'z'),
            Map.entry('ʑ', 'z'),
            Map.entry('ʗ', 'c'),
            Map.entry('ʙ', 'B'),
            Map.entry('ʚ', 'e'),
            Map.entry('ẚ', 'a'),
            Map.entry('ʛ', 'G'),
            Map.entry('ẛ', 's'),
            Map.entry('ʜ', 'H'),
            Map.entry('ʝ', 'j'),
            Map.entry('ʞ', 'k'),
            Map.entry('ʟ', 'L'),
            Map.entry('ʠ', 'q'),
            Map.entry('ʮ', 'h'),
            Map.entry('！', '!'),
            Map.entry('＂', '"'),
            Map.entry('＃', '#'),
            Map.entry('＄', '$'),
            Map.entry('％', '%'),
            Map.entry('＆', '&'),
            Map.entry('＇', '\''),
            Map.entry('（', '('),
            Map.entry('）', ')'),
            Map.entry('＊', '*'),
            Map.entry('＋', '+'),
            Map.entry('，', ','),
            Map.entry('－', '-'),
            Map.entry('．', '.'),
            Map.entry('／', '/'),
            Map.entry('０', '0'),
            Map.entry('１', '1'),
            Map.entry('２', '2'),
            Map.entry('３', '3'),
            Map.entry('４', '4'),
            Map.entry('５', '5'),
            Map.entry('６', '6'),
            Map.entry('７', '7'),
            Map.entry('８', '8'),
            Map.entry('９', '9'),
            Map.entry('：', ','),
            Map.entry('；', ';'),
            Map.entry('＜', '<'),
            Map.entry('＝', '='),
            Map.entry('＞', '>'),
            Map.entry('？', '?'),
            Map.entry('＠', '@'),
            Map.entry('Ａ', 'A'),
            Map.entry('Ｂ', 'B'),
            Map.entry('Ｃ', 'C'),
            Map.entry('Ｄ', 'D'),
            Map.entry('Ｅ', 'E'),
            Map.entry('Ｆ', 'F'),
            Map.entry('Ｇ', 'G'),
            Map.entry('Ｈ', 'H'),
            Map.entry('Ｉ', 'I'),
            Map.entry('Ｊ', 'J'),
            Map.entry('Ｋ', 'K'),
            Map.entry('Ｌ', 'L'),
            Map.entry('Ｍ', 'M'),
            Map.entry('Ｎ', 'N'),
            Map.entry('Ｏ', 'O'),
            Map.entry('Ｐ', 'P'),
            Map.entry('Ｑ', 'Q'),
            Map.entry('Ｒ', 'R'),
            Map.entry('Ｓ', 'S'),
            Map.entry('Ｔ', 'T'),
            Map.entry('Ｕ', 'U'),
            Map.entry('Ｖ', 'V'),
            Map.entry('Ｗ', 'W'),
            Map.entry('Ｘ', 'X'),
            Map.entry('Ｙ', 'Y'),
            Map.entry('Ｚ', 'Z'),
            Map.entry('［', '['),
            Map.entry('＼', '\\'),
            Map.entry('］', ']'),
            Map.entry('＾', '^'),
            Map.entry('＿', '_'),
            Map.entry('｀', '`'),
            Map.entry('ａ', 'a'),
            Map.entry('ｂ', 'b'),
            Map.entry('ｃ', 'c'),
            Map.entry('ｄ', 'd'),
            Map.entry('ｅ', 'e'),
            Map.entry('ｆ', 'f'),
            Map.entry('ｇ', 'g'),
            Map.entry('ｈ', 'h'),
            Map.entry('ｉ', 'i'),
            Map.entry('ｊ', 'j'),
            Map.entry('ｋ', 'k'),
            Map.entry('ｌ', 'l'),
            Map.entry('ｍ', 'm'),
            Map.entry('ｎ', 'n'),
            Map.entry('ｏ', 'o'),
            Map.entry('ｐ', 'p'),
            Map.entry('ｑ', 'q'),
            Map.entry('ｒ', 'r'),
            Map.entry('ｓ', 's'),
            Map.entry('ｔ', 't'),
            Map.entry('ｕ', 'u'),
            Map.entry('ｖ', 'v'),
            Map.entry('ｗ', 'w'),
            Map.entry('ｘ', 'x'),
            Map.entry('ｙ', 'y'),
            Map.entry('ｚ', 'z'),
            Map.entry('｛', '{'),
            Map.entry('｜', '|'),
            Map.entry('｝', '}'),
            Map.entry('～', '~'),
            Map.entry('｡', '.'),
            Map.entry('ͣ', 'a'),
            Map.entry('ͤ', 'e'),
            Map.entry('ͥ', 'i'),
            Map.entry('ͦ', 'o'),
            Map.entry('ͧ', 'u'),
            Map.entry('ͨ', 'c'),
            Map.entry('ͩ', 'd'),
            Map.entry('ͪ', 'h'),
            Map.entry('ͫ', 'm'),
            Map.entry('ͬ', 'r'),
            Map.entry('ͭ', 't'),
            Map.entry('ͮ', 'v'),
            Map.entry('ͯ', 'x')
            ));

    public static String normalize(String filename) {
        filename = Normalizer.normalize(filename, Normalizer.Form.NFD).replaceAll("\\p{M}", "");
        char[] ret = filename.toCharArray(); // copy the array

        for (int i = 0; i < filename.length(); i++) {
            char r = filename.charAt(i);

            // Only handle the range 0x00C0–0xFF61
            if (r < 'À' || r > '｡') {
                continue;
            }

            Character n = normalized.get(r);
            if (n != null) {
                ret[i] = n;
            }
        }
        return new String(ret);
    }

    // Example usage
    public static void main(String[] args) {
        String text = "áăǎâ";
        String normalizedText = normalize(text);
        System.out.println(normalizedText);
    }
}
